/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package getfast;
import com.sun.xml.internal.ws.wsdl.writer.document.Fault;
import java.lang.Math;
import java.util.Timer;
import java.util.TimerTask;
/**
 *
 * @author Jimin Wen
 * easy mode 
 */
public class Easymode extends javax.swing.JFrame {
   
    /**
     * Creates new form Easymode to initial all the components 
     */
    public Easymode() {
        initComponents();
        penal1.set_mode(0);
        randomshape1.set_mode(0);
        randomshape1.repaint();
        mark=0;
        timeremain=60;
        jLabel4.setText(" "+timeremain);
        jLabel5.setText(" "+mark);
        mytimer=new Timer();
        mytimer.scheduleAtFixedRate(mytask, 1000, 1000);
        Sound.Sound4.loop();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jToggleButton1 = new javax.swing.JToggleButton();
        jInternalFrame1 = new javax.swing.JInternalFrame();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jInternalFrame2 = new javax.swing.JInternalFrame();
        jLabel6 = new javax.swing.JLabel();
        randomshape1 = new getfast.Requiredshape();
        penal1 = new getfast.Penal();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1366, 768));
        setPreferredSize(new java.awt.Dimension(448, 313));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setFont(new java.awt.Font("宋体", 0, 48)); // NOI18N
        jButton1.setText("Main menu");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 10, -1, -1));

        jButton2.setFont(new java.awt.Font("宋体", 0, 48)); // NOI18N
        jButton2.setText("Pause");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, -1, -1));

        jToggleButton1.setFont(new java.awt.Font("宋体", 0, 48)); // NOI18N
        jToggleButton1.setText("Sound");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jToggleButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 10, -1, -1));

        jInternalFrame1.setVisible(true);

        jLabel2.setFont(new java.awt.Font("宋体", 0, 36)); // NOI18N
        jLabel2.setText("Mark");

        jLabel3.setFont(new java.awt.Font("宋体", 0, 36)); // NOI18N
        jLabel3.setText("Time remained");

        jLabel4.setFont(new java.awt.Font("宋体", 0, 36)); // NOI18N
        jLabel4.setText("jLabel4");

        jLabel5.setFont(new java.awt.Font("宋体", 0, 36)); // NOI18N
        jLabel5.setText("jLabel5");

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(jLabel3))
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addGap(118, 118, 118)
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel5)
                                .addComponent(jLabel4)))))
                .addContainerGap(85, Short.MAX_VALUE))
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel3)
                .addGap(38, 38, 38)
                .addComponent(jLabel4)
                .addGap(41, 41, 41)
                .addComponent(jLabel2)
                .addGap(26, 26, 26)
                .addComponent(jLabel5)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        getContentPane().add(jInternalFrame1, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, -30, 380, 360));

        jButton3.setFont(new java.awt.Font("宋体", 0, 48)); // NOI18N
        jButton3.setLabel("Restart");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 10, -1, -1));

        jInternalFrame2.setVisible(true);

        jLabel6.setFont(new java.awt.Font("宋体", 0, 36)); // NOI18N
        jLabel6.setText("Required Shape");

        javax.swing.GroupLayout randomshape1Layout = new javax.swing.GroupLayout(randomshape1);
        randomshape1.setLayout(randomshape1Layout);
        randomshape1Layout.setHorizontalGroup(
            randomshape1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 238, Short.MAX_VALUE)
        );
        randomshape1Layout.setVerticalGroup(
            randomshape1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 189, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jInternalFrame2Layout = new javax.swing.GroupLayout(jInternalFrame2.getContentPane());
        jInternalFrame2.getContentPane().setLayout(jInternalFrame2Layout);
        jInternalFrame2Layout.setHorizontalGroup(
            jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame2Layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(randomshape1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        jInternalFrame2Layout.setVerticalGroup(
            jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame2Layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(randomshape1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jInternalFrame2, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 330, -1, 360));

        penal1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                penal1MousePressed(evt);
            }
        });

        javax.swing.GroupLayout penal1Layout = new javax.swing.GroupLayout(penal1);
        penal1.setLayout(penal1Layout);
        penal1Layout.setHorizontalGroup(
            penal1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 990, Short.MAX_VALUE)
        );
        penal1Layout.setVerticalGroup(
            penal1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );

        getContentPane().add(penal1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 990, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

   /**
     * enter the pause interface when the pause button is clicked
     * @param evt 
     */
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    pause=1;
    mytimer.cancel();
    Pause relax=new Pause();
    relax.set_mode(0);
    relax.storeeasy(this);
    relax.setVisible(true);
    dispose();
    }//GEN-LAST:event_jButton2ActionPerformed
/**
 * Return to the main menu when click "main menu" button
 * @param evt 
 */
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    mytimer.cancel();
    Maininterface j=new Maininterface();
    j.setVisible(true);
    dispose();// TODO add your handling code here:
    Sound.Sound4.stop();
    }//GEN-LAST:event_jButton1ActionPerformed
/**
 * Restart the game when "restart" button is clicked
 * @param evt 
 */
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
    mytimer.cancel();
    Easymode a=new Easymode();
    a.setVisible(true);
    dispose();// TODO add your handling code here:
    
    }//GEN-LAST:event_jButton3ActionPerformed
    /**
     * Switch on\off when "sound" button is clicked
     * @param evt 
     */
    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
    if(sound==1){sound=0;Sound.Sound4.stop();}
    else{sound=1;Sound.Sound4.loop();}// TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void penal1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_penal1MousePressed
    cx=evt.getX();
    cy=evt.getY();
    System.out.println("cx="+cx);
    System.out.println("cy="+cy);
    if ((cx>penal1.x1)&&(cx<penal1.x1+60)&&(cy>penal1.y1)&&(cy<penal1.y1+60))//Judge whether a right click is taken
    {
    penal1.x1=penal1.rand.nextInt(900);
    penal1.y1=penal1.rand.nextInt(550);
    System.out.println("start");
    System.out.println("x="+penal1.x1);     
    System.out.println("y="+penal1.y1);    
    penal1.repaint();
    mark+=1;
    jLabel5.setText(" "+mark);
    if(sound==1){Sound.Sound5.play();}
    }                    // TODO add your handling code here:
    }//GEN-LAST:event_penal1MousePressed
    /**
     * restart the timer when switching from the pause interface to the easymode interface
     */
    public void set_pause()
    {
        pause=0;
        mytimer=new Timer();
        mytask=new Timertask()
          {
         public void run()
         {
         System.out.println("refresh");
          if (pause==0)
         {
         timeremain-=1;
         }
        jLabel4.setText(" "+timeremain);
        if (timeremain==0)//The game ends
        {
         showmark newmark=new showmark();
         newmark.set_mark(mark);
         newmark.setVisible(true);
         mytimer.cancel();
         dispose();
         
        }
        }
        };
        mytimer.scheduleAtFixedRate(mytask, 1000, 1000);
       
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Easymode.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Easymode.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Easymode.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Easymode.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } 
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Easymode().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JInternalFrame jInternalFrame2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JToggleButton jToggleButton1;
    private getfast.Penal penal1;
    private getfast.Requiredshape randomshape1;
    // End of variables declaration//GEN-END:variables
    private int mark;
    private int timeremain;
    private int cx,cy;
    private int pause=0;
    int sound=1;
    private Timer mytimer;
    TimerTask mytask=new Timertask()//A timer to manage the game
    {
     public void run()
     {
     System.out.println("refresh");
     if (pause==0)
     {
         timeremain-=1;
     }
     jLabel4.setText(" "+timeremain);
     if (timeremain==0)
     {   Sound.Sound4.stop();
         showmark newmark=new showmark();
         newmark.set_mark(mark);
         newmark.setVisible(true);
         mytimer.cancel();
         dispose();
         
      }
     }
    };
  

  
}
