/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package getfast;

import java.util.Timer;
import java.util.TimerTask;

/**
 *
 * @author Jimin Wen
 * hard mode
 */
public class Hardmode extends javax.swing.JFrame {

    /**
     * Creates new form Hardmode
     */
    public Hardmode() {
        initComponents();
        randomshape1.set_mode(2);
        hardshape1.set_mode(2);
        jLabel4.setText(" "+time);
        jLabel5.setText(" "+mark);
        mytimer1=new Timer();
        mytimer1.scheduleAtFixedRate(mytask1, 1000, 1000);
        Sound.Sound4.loop();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jToggleButton1 = new javax.swing.JToggleButton();
        jInternalFrame1 = new javax.swing.JInternalFrame();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jInternalFrame2 = new javax.swing.JInternalFrame();
        jLabel6 = new javax.swing.JLabel();
        randomshape1 = new getfast.Requiredshape();
        hardshape1 = new getfast.Penal();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1387, 768));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setFont(new java.awt.Font("宋体", 0, 48)); // NOI18N
        jButton1.setLabel("Restart");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 10, -1, -1));

        jButton2.setFont(new java.awt.Font("宋体", 0, 48)); // NOI18N
        jButton2.setText("Pause");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jToggleButton1.setFont(new java.awt.Font("宋体", 0, 48)); // NOI18N
        jToggleButton1.setText("Sound");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jToggleButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 10, -1, -1));

        jInternalFrame1.setVisible(true);

        jLabel2.setFont(new java.awt.Font("宋体", 0, 36)); // NOI18N
        jLabel2.setText("Mark");

        jLabel3.setFont(new java.awt.Font("宋体", 0, 36)); // NOI18N
        jLabel3.setText("Time remained");

        jLabel4.setFont(new java.awt.Font("宋体", 0, 36)); // NOI18N
        jLabel4.setText("jLabel4");

        jLabel5.setFont(new java.awt.Font("宋体", 0, 36)); // NOI18N
        jLabel5.setText("jLabel5");

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jInternalFrame1Layout.createSequentialGroup()
                .addGap(0, 74, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(66, 66, 66))
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addGap(117, 117, 117)
                        .addComponent(jLabel5))
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel3)
                .addGap(36, 36, 36)
                .addComponent(jLabel4)
                .addGap(44, 44, 44)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        getContentPane().add(jInternalFrame1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 0, 390, 350));

        jInternalFrame2.setVisible(true);

        jLabel6.setFont(new java.awt.Font("宋体", 0, 36)); // NOI18N
        jLabel6.setText("Required Shape");

        javax.swing.GroupLayout randomshape1Layout = new javax.swing.GroupLayout(randomshape1);
        randomshape1.setLayout(randomshape1Layout);
        randomshape1Layout.setHorizontalGroup(
            randomshape1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 187, Short.MAX_VALUE)
        );
        randomshape1Layout.setVerticalGroup(
            randomshape1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 182, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jInternalFrame2Layout = new javax.swing.GroupLayout(jInternalFrame2.getContentPane());
        jInternalFrame2.getContentPane().setLayout(jInternalFrame2Layout);
        jInternalFrame2Layout.setHorizontalGroup(
            jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jInternalFrame2Layout.createSequentialGroup()
                .addContainerGap(67, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(55, 55, 55))
            .addGroup(jInternalFrame2Layout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addComponent(randomshape1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jInternalFrame2Layout.setVerticalGroup(
            jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame2Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel6)
                .addGap(32, 32, 32)
                .addComponent(randomshape1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        getContentPane().add(jInternalFrame2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 350, -1, 350));

        hardshape1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                hardshape1MousePressed(evt);
            }
        });

        javax.swing.GroupLayout hardshape1Layout = new javax.swing.GroupLayout(hardshape1);
        hardshape1.setLayout(hardshape1Layout);
        hardshape1Layout.setHorizontalGroup(
            hardshape1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 999, Short.MAX_VALUE)
        );
        hardshape1Layout.setVerticalGroup(
            hardshape1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 620, Short.MAX_VALUE)
        );

        getContentPane().add(hardshape1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, -1, 620));

        jButton3.setFont(new java.awt.Font("宋体", 0, 48)); // NOI18N
        jButton3.setText("Main menu");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 10, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents
/**
 * Decide whether required shape is clicked and take corresponding actions.
 * If wrong object is clicked, mark is reduced.
 * @param evt 
 */
    private void hardshape1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hardshape1MousePressed
    cx=evt.getX();
    cy=evt.getY();
    ID=randomshape1.get_id();
     if ((cx>hardshape1.x1)&&(cx<hardshape1.x1+60)&&(cy>hardshape1.y1)&&(cy<hardshape1.y1+60))
    {
        if (ID==0){judge=1;}
        else {judge=0;}
    }
     else if ((cx>hardshape1.x2)&&(cx<hardshape1.x2+60)&&(cy>hardshape1.y2)&&(cy<hardshape1.y2+60))
    {
        if (ID==1){judge=1;}
        else {judge=0;}
    }
     else   if ((cx>hardshape1.x3)&&(cx<hardshape1.x3+60)&&(cy>hardshape1.y3)&&(cy<hardshape1.y3+60))
    {
        if (ID==2){judge=1;}
        else {judge=0;}
    }
      else    if ((cx>hardshape1.x4)&&(cx<hardshape1.x4+60)&&(cy>hardshape1.y4)&&(cy<hardshape1.y4+60))
    {
        if (ID==3){judge=1;}
        else {judge=0;}
    }
      else
      {
       judge=-1;   
      }
        if (judge==1)
        {   
            if(sound==1){Sound.Sound5.play();}
            count=0;
            mark+=1;
            jLabel5.setText(" "+mark);
            hardshape1.x1=hardshape1.rand.nextInt(900);
            hardshape1.y1=hardshape1.rand.nextInt(550);
            hardshape1.x2=hardshape1.rand.nextInt(900);
            hardshape1.y2=hardshape1.rand.nextInt(550);
            hardshape1.x3=hardshape1.rand.nextInt(900);
            hardshape1.y3=hardshape1.rand.nextInt(550);
            hardshape1.x4=hardshape1.rand.nextInt(900);
            hardshape1.y4=hardshape1.rand.nextInt(550);
            hardshape1.repaint();
            randomshape1.shapeid=randomshape1.rand.nextInt(4);
            randomshape1.repaint();
        }
        
        if (judge==0)
        {
              mark-=1;
              jLabel5.setText(" "+mark);
              
        }
    }//GEN-LAST:event_hardshape1MousePressed
/**
 * restart the game when "restart" button is clicked
 * @param evt 
 */
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
     mytimer1.cancel();
     Hardmode h=new Hardmode();
     h.setVisible(true);
     dispose();// TODO add your handling code here:
     
    }//GEN-LAST:event_jButton1ActionPerformed
/**
 * Enter the pause interface if "pause" button is clicked.
 * @param evt 
 */
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    pause=1;
    mytimer1.cancel();
    Pause relax=new Pause();
    relax.set_mode(2);
    relax.storehard(this);
    relax.setVisible(true);
    dispose();      // TODO add your handling code here:
     
    }//GEN-LAST:event_jButton2ActionPerformed
/**
 * Back to main menu if "mainmenu" button is clicked
 * @param evt 
 */
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
    Maininterface j=new Maininterface();
    mytimer1.cancel();
    j.setVisible(true);
    dispose();//        // TODO add your handling code here:
    Sound.Sound4.stop();
    }//GEN-LAST:event_jButton3ActionPerformed
/**
 * Switching on/off sound when "sound" button is clicked
 * @param evt 
 */
    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
    if (sound==1){Sound.Sound4.stop();sound=0;}
    else{sound=1;Sound.Sound4.loop();}// TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Hardmode.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Hardmode.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Hardmode.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Hardmode.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Hardmode().setVisible(true);
            }
        });
    }
    /**
     * restart the timer when "resume" in the pause interface is clicked
     */
      public void set_pause()
    {
        pause=0;
        mytimer1=new Timer();
        mytask1=new Timertask()
    {
     public void run()
     {
     System.out.println("refresh");
     if (pause==0)
     {time-=1;}
     jLabel4.setText(" "+time);
     count+=1;
     if ((count%2==0)&&(count!=0))
     {
    // System.out.println("refresh!!"+count);
     hardshape1.x1=hardshape1.rand.nextInt(900);
     hardshape1.y1=hardshape1.rand.nextInt(550);
     hardshape1.x2=hardshape1.rand.nextInt(900);
     hardshape1.y2=hardshape1.rand.nextInt(550);
     hardshape1.x3=hardshape1.rand.nextInt(900);
     hardshape1.y3=hardshape1.rand.nextInt(550);
     hardshape1.x4=hardshape1.rand.nextInt(900);
     hardshape1.y4=hardshape1.rand.nextInt(550);
     hardshape1.repaint();
     randomshape1.shapeid=randomshape1.rand.nextInt(4);
     randomshape1.repaint();
       
         
     }
     if (time==0)
     {
       
         showmark newmark=new showmark();
         newmark.set_mark(mark);
      
         newmark.setVisible(true);
         mytimer1.cancel();
         dispose();
      }
     }
    };
         mytimer1.scheduleAtFixedRate(mytask1, 1000, 1000);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private getfast.Penal hardshape1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JInternalFrame jInternalFrame2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JToggleButton jToggleButton1;
    private getfast.Requiredshape randomshape1;
    // End of variables declaration//GEN-END:variables
    private int pause=0;
    int time=60;
    int mark=0;
    int cx;
    int cy;
    int ID;
    int judge;
    int count=0;
    int sound=1;
    Timer mytimer1;
    TimerTask mytask1=new Timertask()
    {
     public void run()
     {
     System.out.println("refresh");
     if (pause==0)
     {time-=1;}
     jLabel4.setText(" "+time);
     count+=1;
     if ((count%2==0)&&(count!=0))
     {
    // System.out.println("refresh!!"+count);
     hardshape1.x1=hardshape1.rand.nextInt(900);
     hardshape1.y1=hardshape1.rand.nextInt(550);
     hardshape1.x2=hardshape1.rand.nextInt(900);
     hardshape1.y2=hardshape1.rand.nextInt(550);
     hardshape1.x3=hardshape1.rand.nextInt(900);
     hardshape1.y3=hardshape1.rand.nextInt(550);
     hardshape1.x4=hardshape1.rand.nextInt(900);
     hardshape1.y4=hardshape1.rand.nextInt(550);
     hardshape1.repaint();
     randomshape1.shapeid=randomshape1.rand.nextInt(4);
     randomshape1.repaint();
       
         
     }
     if (time==0)
     {
         Sound.Sound4.stop();
         showmark newmark=new showmark();
         newmark.set_mark(mark);
      
         newmark.setVisible(true);
         mytimer1.cancel();
         dispose();
      }
     }
    };
}
