/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package getfast;

import java.util.Timer;
import java.util.TimerTask;

/**
 *
 * @author Jimin Wen
 * the medium mode in the game
 */
public class Mediummode extends javax.swing.JFrame {
     int a=1;
    /**
     * Creates new form Middlemode
     */
    public Mediummode() {
        initComponents();
        penal1.set_mode(1);
        randomshape1.set_mode(1);
        mytimerm=new Timer();
        jLabel4.setText("  "+time);
        jLabel5.setText("  "+marks);
        mytimerm.scheduleAtFixedRate(mytask1, 1000, 1000);
        Sound.Sound4.loop();
     //   mytimerm.cancel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrame2 = new javax.swing.JInternalFrame();
        jLabel6 = new javax.swing.JLabel();
        randomshape1 = new getfast.Requiredshape();
        jInternalFrame1 = new javax.swing.JInternalFrame();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jToggleButton1 = new javax.swing.JToggleButton();
        penal1 = new getfast.Penal();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1366, 768));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jInternalFrame2.setVisible(true);

        jLabel6.setFont(new java.awt.Font("宋体", 0, 36)); // NOI18N
        jLabel6.setText("Required Shape");

        javax.swing.GroupLayout randomshape1Layout = new javax.swing.GroupLayout(randomshape1);
        randomshape1.setLayout(randomshape1Layout);
        randomshape1Layout.setHorizontalGroup(
            randomshape1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 235, Short.MAX_VALUE)
        );
        randomshape1Layout.setVerticalGroup(
            randomshape1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 192, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jInternalFrame2Layout = new javax.swing.GroupLayout(jInternalFrame2.getContentPane());
        jInternalFrame2.getContentPane().setLayout(jInternalFrame2Layout);
        jInternalFrame2Layout.setHorizontalGroup(
            jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jInternalFrame2Layout.createSequentialGroup()
                .addContainerGap(69, Short.MAX_VALUE)
                .addGroup(jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(randomshape1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(43, 43, 43))
        );
        jInternalFrame2Layout.setVerticalGroup(
            jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame2Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(randomshape1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        getContentPane().add(jInternalFrame2, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 340, 380, 360));

        jInternalFrame1.setVisible(true);

        jLabel2.setFont(new java.awt.Font("宋体", 0, 36)); // NOI18N
        jLabel2.setText("Mark");

        jLabel3.setFont(new java.awt.Font("宋体", 0, 36)); // NOI18N
        jLabel3.setText("Time remained");

        jLabel4.setFont(new java.awt.Font("宋体", 0, 36)); // NOI18N
        jLabel4.setText("jLabel4");

        jLabel5.setFont(new java.awt.Font("宋体", 0, 36)); // NOI18N
        jLabel5.setText("jLabel5");

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addGap(118, 118, 118)
                        .addComponent(jLabel2))
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(jLabel3))
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4))))
                .addContainerGap(76, Short.MAX_VALUE))
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel3)
                .addGap(40, 40, 40)
                .addComponent(jLabel4)
                .addGap(40, 40, 40)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addContainerGap(104, Short.MAX_VALUE))
        );

        getContentPane().add(jInternalFrame1, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, -20, 380, 420));

        jButton1.setFont(new java.awt.Font("宋体", 0, 48)); // NOI18N
        jButton1.setText("Pause");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jButton2.setFont(new java.awt.Font("宋体", 0, 48)); // NOI18N
        jButton2.setText("Main Menu");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 10, -1, -1));

        jButton3.setFont(new java.awt.Font("宋体", 0, 48)); // NOI18N
        jButton3.setText("Restart");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 10, -1, -1));

        jToggleButton1.setFont(new java.awt.Font("宋体", 0, 48)); // NOI18N
        jToggleButton1.setText("Sound");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jToggleButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 10, -1, -1));

        penal1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                penal1MousePressed(evt);
            }
        });

        javax.swing.GroupLayout penal1Layout = new javax.swing.GroupLayout(penal1);
        penal1.setLayout(penal1Layout);
        penal1Layout.setHorizontalGroup(
            penal1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 990, Short.MAX_VALUE)
        );
        penal1Layout.setVerticalGroup(
            penal1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 620, Short.MAX_VALUE)
        );

        getContentPane().add(penal1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 990, 620));

        pack();
    }// </editor-fold>//GEN-END:initComponents


    
    
    /**
     * enter the pause interface when "pause" button is pressed
     * @param evt 
     */
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    pause=1;
    mytimerm.cancel();
    Pause relax=new Pause();
    relax.set_mode(1);
    relax.storemiddle(this);
    relax.setVisible(true);
    dispose();  // TODO add your handling code here:
    
    }//GEN-LAST:event_jButton1ActionPerformed
/**
 * back to main menu when "main menu" button is pressed
 * @param evt 
 */
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    mytimerm.cancel();
    Maininterface j=new Maininterface();
    j.setVisible(true);
    dispose();//        // TODO add your handling code here:
    Sound.Sound4.stop();
    }//GEN-LAST:event_jButton2ActionPerformed
/**
 * enter the middle mode when "middle mode" button is pressed
 * @param evt 
 */
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
    mytimerm.cancel();
    Mediummode m=new Mediummode();
    m.setVisible(true);
    dispose();// TODO add your handling code here:
    
    }//GEN-LAST:event_jButton3ActionPerformed
/**
 * switching on\off the sound
 * @param evt 
 */
    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
    if(sound==1){sound=0;Sound.Sound4.stop();}
    else{sound=1;Sound.Sound4.loop();}// TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void penal1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_penal1MousePressed
      cx=evt.getX();
    cy=evt.getY();
    if ((cx>penal1.x1)&&(cx<penal1.x1+60)&&(cy>penal1.y1)&&(cy<penal1.y1+60))
    {    
        count=0;
         marks+=1;
         jLabel5.setText(" "+marks);
         penal1.x1=penal1.rand.nextInt(900);
         penal1.y1=penal1.rand.nextInt(550);
         penal1.x2=penal1.rand.nextInt(900);
         penal1.y2=penal1.rand.nextInt(550);
         penal1.repaint();
         if(sound==1){Sound.Sound5.play();}
    }                                          
 if ((cx>penal1.x2)&&(cx<penal1.x2+60)&&(cy>penal1.y2)&&(cy<penal1.y2+60))
    { 
         marks-=1;
         jLabel5.setText(" "+marks);
    }    // TODO add your handling code here:
    }//GEN-LAST:event_penal1MousePressed
/**
 * restart the timer when clicking "resume" in the pause interface
 */
    public void set_pause()
    {
        pause=0;
        mytimerm=new Timer();
        mytask1=new Timertask()
    {
     public void run()
     {  
     
     System.out.println(" "+time);
     if (pause==0)
     {
         time-=1;
     }
     jLabel4.setText(" "+time);
     count+=1;
     if ((count%2==0)&&(count!=0))
     {
     System.out.println("refresh!!"+count);
     penal1.x1=penal1.rand.nextInt(900);
     penal1.y1=penal1.rand.nextInt(550);
     penal1.x2=penal1.rand.nextInt(900);
     penal1.y2=penal1.rand.nextInt(550);
     penal1.repaint();
     }
     if (time==0)
     {
      
      showmark another=new showmark();  
      another.set_mark(marks);
      another.setVisible(true);
      
      dispose();
      
      }
     }
    };
        mytimerm.scheduleAtFixedRate(mytask1, 1000, 1000);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Mediummode.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Mediummode.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Mediummode.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Mediummode.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Mediummode().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JInternalFrame jInternalFrame2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JToggleButton jToggleButton1;
    private getfast.Penal penal1;
    private getfast.Requiredshape randomshape1;
    // End of variables declaration//GEN-END:variables
    private int pause=0;
    private int time=60;
    private int marks=0;
    int sound=1;
   // private Timer mytimerm=new Timer();
    private Timer mytimerm;
    /**
     * set the timer task
     */
    TimerTask mytask1=new Timertask()
    {
     public void run()
     {  
     
     System.out.println(" "+time);
     if (pause==0)
     {
         time-=1;
     }
     jLabel4.setText(" "+time);
     count+=1;
     if ((count%2==0)&&(count!=0))
     {
     System.out.println("refresh!!"+count);
     penal1.x1=penal1.rand.nextInt(900);
     penal1.y1=penal1.rand.nextInt(550);
     penal1.x2=penal1.rand.nextInt(900);
     penal1.y2=penal1.rand.nextInt(550);
     penal1.repaint();
     }
     if (time==0)
     {
      Sound.Sound4.stop();
      mytimerm.cancel();
      showmark another=new showmark();  
      another.set_mark(marks);
      another.setVisible(true);
      
      dispose();
      
      }
     }
    };
    int cx;
    int cy;
    int count=0;
}
