/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package getfast;

import javax.swing.JFrame;

/**
 *
 * @author Jimin Wen
 * the pause interface
 */
public class Pause extends javax.swing.JFrame {

    /**
     * Creates new form Pause
     */
    public Pause() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("宋体", 0, 48)); // NOI18N
        jLabel1.setText("Pause");

        jButton1.setFont(new java.awt.Font("宋体", 0, 48)); // NOI18N
        jButton1.setText("Restart");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("宋体", 0, 48)); // NOI18N
        jButton2.setText("Resume");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("宋体", 0, 48)); // NOI18N
        jButton4.setText("Main menu");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(582, 582, 582)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(515, 515, 515)
                        .addComponent(jButton4))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(532, 532, 532)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(jButton2)))))
                .addContainerGap(597, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addComponent(jLabel1)
                .addGap(106, 106, 106)
                .addComponent(jButton2)
                .addGap(86, 86, 86)
                .addComponent(jButton1)
                .addGap(98, 98, 98)
                .addComponent(jButton4)
                .addContainerGap(146, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
/**
 * resume to the game when "resume" button has been clicked
 * @param evt 
 */
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    if (mode==0)
    {
        Easymode e=new Easymode();
        e.setVisible(true);
        dispose();
    }  
     if (mode==1)
    {
        Mediummode e=new Mediummode();
        e.setVisible(true);
        dispose();
    }  
      if (mode==2)
    {
        Hardmode e=new Hardmode();
        e.setVisible(true);
        dispose();
    }  
       if(mode==3)
       {
         Specialmode s=new Specialmode();
         s.setVisible(true);
         dispose();
       }
// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed
/**
 * back to the main menu when "main menu" button has been clicked
 * @param evt 
 */
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
    if (mode==3){Sound.Sound2.stop();}
    else{Sound.Sound4.stop();}
    Maininterface j=new Maininterface();
    j.setVisible(true);
    dispose();//        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed
/**
 * restart a game when "restart" has been clicked
 * @param evt 
 */
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
//    j.setpause();
  //  j.setVisible(true);
    if (mode==0)
    {
        easymode.set_pause();
        easymode.setVisible(true);
      
    }
      if (mode==1)
    {
        middlemode.set_pause();
        middlemode.setVisible(true);
      
    }
        if (mode==2)
    {
        hardmode.set_pause();
        hardmode.setVisible(true);
         
    }
        if (mode==3)
    {
       specialmode.set_pause();
       specialmode.setVisible(true);
       
    }
    dispose();// TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed
    /**
     * recode the mode of the game when entering the pause
     * @param a 
     */
    public void set_mode(int a)
    {
        mode=a;
    }
    public void storeeasy(Easymode nj)
    { easymode=nj;
        
    }   
    public void storemiddle(Mediummode nj)
    { middlemode=nj;
        
    } 
    public void storehard(Hardmode nj)
    { hardmode=nj;
        
    } 
    public void storespecial(Specialmode nj)
    {
        specialmode=nj;
    }
    public void store(JFrame nj)
    {
        j=nj;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pause.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pause.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pause.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pause.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pause().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
    int mode;
    Easymode easymode;
    Mediummode middlemode;
    Hardmode hardmode;
    Specialmode specialmode;
    JFrame j;

}
