/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package getfast;

import java.awt.Color;
import java.awt.Graphics;
import java.util.Random;

/**
 *
 * @author Jimin Wen
 * the penal to draw objects in easy mode, middium mode and hard mode in the operation area. 
 */
public class Penal extends javax.swing.JPanel {
    int x1,y1,x2,y2,x3,y3,x4,y4;
    Random rand;
    int mode;
    /**
     * Creates new form Hardshape
     */
    public Penal() {
        initComponents();
        rand= new Random();
        x1=rand.nextInt(900);
        y1=rand.nextInt(550);
        x2=rand.nextInt(900);
        y2=rand.nextInt(550);
        x3=rand.nextInt(900);
        y3=rand.nextInt(550);
        x4=rand.nextInt(900);
        y4=rand.nextInt(550);
        repaint();
    }
    /**
     * stored the mode of the game 
     * @param a 
     */
    void set_mode(int a)
    {
      mode=a;  
    }
    /**
     * Objects on drawn in the screen
     * The objects drawn are different in different modes of the game
     * @param g 
     */
     @Override
    public void paintComponent(Graphics g)
    {   
             
        super.paintComponent(g);
        if (mode==0)
        {
        g.fillRect(x1, y1, 60, 60);    
        }
        if (mode==1)
        {
        g.fillRect(x1, y1, 60, 60);
        g.fillOval(x2, y2, 60, 60);    
        }
        if(mode==2)
        {
        g.fillRect(x1, y1, 60, 60);
        g.fillOval(x2, y2, 60, 60);
        g.setColor(Color.blue);
        g.fillRect(x3, y3, 60, 60);
        g.fillOval(x4, y4, 60, 60);
        }
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
