/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package getfast;

import java.awt.Color;
import java.awt.Graphics;
import java.util.Random;


/**
 *
 * @author Jimin Wen
 * The required shape to be clicked in the game
 */
public class Requiredshape extends javax.swing.JPanel {
    int shapeid;
    Random rand;
    int mode;
    /**
     * Creates new form Randomshape
     */
    public Requiredshape() {
        initComponents();
        rand= new Random();
        shapeid=rand.nextInt(4);
        repaint();
    }
    /**
     * record the mode of the game
     * @param a 
     */
    void set_mode(int a)
    {
        mode=a;
    }
    /**
     * return the id of the random shape
     * @return 
     */
    int get_id()
    {
        return shapeid;
    }
    /**
     * show the required shape in this penal
     * @param g 
     */
@Override
    public void paintComponent(Graphics g)
    {   
             
        super.paintComponent(g);
        if ((mode==0)||(mode==1))
        {
            g.fillRect(50, 50, 100, 100);
        }
        if (mode==2)
        {    
        if (shapeid==0)
        {
            g.fillRect(50, 50, 100, 100);
        }
        if (shapeid==1)
        {
            g.fillOval(50, 50, 100, 100);
        }
        if (shapeid==2)
        {
            g.setColor(Color.blue);
            g.fillRect(50, 50, 100, 100);
        }
        if (shapeid==3)
        {
            g.setColor(Color.blue);
            g.fillOval(50, 50, 100, 100);
        }
        }
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
